name: Rust

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  dry-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dry Release
      run: cargo publish -n
