name: Publish to crates.io

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: publish
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
